# Dev configuration
server:
  port: 8090
security:
  basic:
    enabled: false
  ignored:
    - /**
management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
